# Generated by Django 3.1 on 2020-08-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='priceNew',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='priceOld',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='ratting',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
